### ISSUE TITLE
"foldleft" support?

### ISSUE THREAD

**Issue by threecifanggen** [olirice/flupy#11]
I think `foldleft` summarizing method could be added, because `reduce` requires a function with two same-type parameters. `foldleft`/`foldright` method is more generalizing. The behavior of this API likes what `reduce` does in `functools` module.

```python
## return ["1", "2", "3", "4"]
flu([1, 2, 3, 4])\
 .foldleft(lambda x, y: x + str(y), '')

## same as `functools.reduce`
reduce(lambda x, y: x + str(y), [1, 2, 3, 4], '')
```

**Comment by olirice** [comment]
The implementation of `flu.reduce` is based on `functools.reduce`.

from typeshed, python's `functools.reduce` supports both same and different types
```python
def reduce(function: Callable[[T, T], T], sequence: Iterable[T]) -> T: 

def reduce(function: Callable[[S, T], S], sequence: Iterable[T], initial: S) -> S:
```

In contrast, `flu.reduce` only supports
https://github.com/olirice/flupy/blob/991beb7cab4919c15c9cdcdad54ecf03545dcba9/flupy/fluent.py#L390

I think the right solution would be to add
```python
def fold_left(self: Fluent[T], function: Callable[[S, T], S], initial: S) -> S:
```
That is also implemented in terms of `functools.reduce`.

Based on SO reference below, the academic difference between the `fold_left` and `reduce` is that `reduce` assumes associativity. That assumption enables parallelism. Given that `functools.reduce` executes sequentially, they are interchangeable.

Assuming you agree with ^, Would you be interested in opening a PR? If not, I'm happy to knock it out within a few days.

**References**:

Explanation of reduce vs fold
https://stackoverflow.com/questions/25158780/difference-between-reduce-and-foldleft-fold-in-functional-programming-particula/25158790

Typeshed type definition of `functools.reduce`
https://github.com/python/typeshed/blob/d21370965aa2a1711d6986e509e43d651f2e3411/stdlib/3/functools.pyi#L10

Example implementation
https://www.burgaud.com/foldl-foldr-python

**Comment by threecifanggen** [comment]
I've implemented a version and opened a PR.
#12
