### ISSUE TITLE
[New Feature] Folding/Reduce

### ISSUE THREAD

**Issue by Mati20041** [olirice/flupy#2]
Hi @olirice very cool project. I've been looking for something like this for some time! Transforming collections in this way wasn't a pleasure for me at all

```python
sum(map(lambda, filter(lambda, list)))
```

I would be glad to see one more function that would be useful - `foldLeft` or `foldRight` or `reduce` as in [scala](https://commitlogs.com/2016/09/10/scala-fold-foldleft-and-foldright/).

Ex.

```python
from flupy import flu
class Collector:
    __init__(self):
        self.nums = []

collector = flu([1,2,3]). \
                 filter(lambda x: x>1). \
                 foldLeft(Collector(), lambda x, acc: acc.nums.append(x))  

assert collector.nums == [2,3]
```

Btw I think that there is a small error in the documentation https://flupy.readthedocs.io/en/latest/api.html#flupy.Fluent.group_by - Shouldn't there be 2 and 3 instead of 4 and 9?

**Comment by olirice** [comment]
Hi @Mati20041

Yes, that was a bug in documentation. Thanks for reporting it!

Reduce is a great idea. I just added it in 913d523020ea6392b06a31f032531a5464b57678 updated the package on pypi.

I'm hesitant to implement foldRight unless someone makes a strong case for it b/c we'd have to load the whole sequence in memory first.
