### ISSUE TITLE
`to_list` and `to_set` not in 1.1.9

### ISSUE THREAD

**Issue by scarf005** [olirice/flupy#26]
`__version__ = "1.1.9"`, docs say there's `to_list` and `to_set`, repository source has both methods, however pypi package doesn't have them.

**Comment by olirice** [comment]
Thanks, I pushed the docs without releasing the latest code that includes `to_list()`

resolving in PR #27 but there's some CI stuff to fix
version 1.2.0 is available on pypi

> and to_set

could you provide a reference to where you're seeing `to_set()`? I don't see it in the docs or the codebase

**Comment by scarf005** [comment]
oh, yeah i've mistaken that it was in the documentation. thanks for updating the package.
