### ISSUE TITLE
empty api reference in doc

### ISSUE THREAD

**Issue by scarf005** [olirice/flupy#28]
![image](https://user-images.githubusercontent.com/54838975/197371577-b23cb912-723a-4a9d-a767-fcb3850a7817.png)
https://flupy.readthedocs.io/en/latest/api.html#grouping

both empty on firefox and chrome.

**Comment by olirice** [comment]
thanks

somethings isn't working with autodoc on readthedocs's build. It wasn't obvious so I'll take a look tomorrow. A text version is attached if you need a reference sooner than then

[api.txt](https://github.com/olirice/flupy/files/9846761/api.txt)

**Comment by olirice** [comment]
API ref docs are back https://flupy.readthedocs.io/en/latest/api.html
